// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ

#include "../ui.h"
#include "../ui_color_arc.h"
#include "bsp_obd_dsp/nvs_storage.h"

#define SPEED_ARC_WIDTH 17

static ui_color_arc_t s_speed_arc;

void ui_speed_arc_set_range(uint16_t min_speed, uint16_t max_speed)
{
    ui_color_arc_set_range(&s_speed_arc, min_speed, max_speed);
}

void ui_speed_arc_set_value(uint16_t speed)
{
    ui_color_arc_set_value(&s_speed_arc, speed);
}

void ui_ScreenPageSpeed_screen_init(void)
{
    ui_ScreenPageSpeed = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPageSpeed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenPageSpeed, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_helpers_style_screen_bg(ui_ScreenPageSpeed);
    lv_obj_set_style_bg_opa(ui_ScreenPageSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    static const ui_color_arc_stop_t speed_stops[] = {
        {0, LV_COLOR_MAKE(0x00, 0xCC, 0x66)},
        {250, LV_COLOR_MAKE(0x00, 0xCC, 0x66)},
        {500, LV_COLOR_MAKE(0xFF, 0xD1, 0x66)},
        {750, LV_COLOR_MAKE(0xFF, 0x8C, 0x42)},
        {1000, LV_COLOR_MAKE(0xFF, 0x4D, 0x4D)},
    };
    const nvs_user_cfg_t *cfg = nvs_cfg_get();
    uint16_t max_speed = cfg->speed_max_kmh;
    if (max_speed < NVS_SPEED_MAX_MIN_KMH || max_speed > NVS_SPEED_MAX_MAX_KMH)
        max_speed = NVS_SPEED_MAX_DEFAULT_KMH;
    ui_color_arc_config_t arc_config = {
        .min_value = 0,
        .max_value = max_speed,
        .size = 230,
        .width = SPEED_ARC_WIDTH,
        .start_angle = 90,
        .track_color = ui_theme_color_lv(UI_COLOR_ARC_TRACK),
        .stops = speed_stops,
        .stop_count = sizeof(speed_stops) / sizeof(speed_stops[0]),
        .slice_count = 32,
    };
    ui_color_arc_create(&s_speed_arc, ui_ScreenPageSpeed, &arc_config);
    ui_SpeedPageArcSpeedBack = s_speed_arc.track;

    ui_LabelSpeedTitle = lv_label_create(ui_ScreenPageSpeed);
    lv_label_set_text(ui_LabelSpeedTitle, "VEHICLE SPEED");
    lv_obj_set_style_text_font(ui_LabelSpeedTitle, &ui_font_FontTypoderSize16, LV_PART_MAIN);
    lv_obj_set_style_text_color(ui_LabelSpeedTitle, ui_theme_color_lv(UI_COLOR_ARC_INDICATOR), LV_PART_MAIN);
    lv_obj_align(ui_LabelSpeedTitle, LV_ALIGN_CENTER, 0, -35);

    ui_SpeedPageArcLabelSpeedText = lv_label_create(ui_ScreenPageSpeed);
    lv_obj_set_width(ui_SpeedPageArcLabelSpeedText, 280);
    lv_obj_set_height(ui_SpeedPageArcLabelSpeedText, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(ui_SpeedPageArcLabelSpeedText, 0);
    lv_obj_set_y(ui_SpeedPageArcLabelSpeedText, 0);
    lv_obj_set_align(ui_SpeedPageArcLabelSpeedText, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_SpeedPageArcLabelSpeedText, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_SpeedPageArcLabelSpeedText, "0");
    lv_obj_set_style_text_align(ui_SpeedPageArcLabelSpeedText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SpeedPageArcLabelSpeedText, ui_theme_color_lv(UI_COLOR_TEXT_PRIMARY), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedPageArcLabelSpeedText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedPageArcLabelSpeedText, &ui_font_FontTypoderSize56, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedPageArcLabelSpeedUnit = lv_label_create(ui_ScreenPageSpeed);
    lv_obj_set_width(ui_SpeedPageArcLabelSpeedUnit, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_SpeedPageArcLabelSpeedUnit, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(ui_SpeedPageArcLabelSpeedUnit, 0);
    lv_obj_set_y(ui_SpeedPageArcLabelSpeedUnit, 38);
    lv_obj_set_align(ui_SpeedPageArcLabelSpeedUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedPageArcLabelSpeedUnit, "km/h");
    lv_obj_set_style_text_color(ui_SpeedPageArcLabelSpeedUnit, ui_theme_color_lv(UI_COLOR_TEXT_PRIMARY), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedPageArcLabelSpeedUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedPageArcLabelSpeedUnit, &ui_font_FontTypoderSize16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSpeedMiniGear = lv_label_create(ui_ScreenPageSpeed);
    lv_label_set_text(ui_LabelSpeedMiniGear, "GEAR --");
    lv_obj_set_width(ui_LabelSpeedMiniGear, 142);
    lv_obj_set_style_text_align(ui_LabelSpeedMiniGear, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_LabelSpeedMiniGear, &ui_font_FontTypoderSize16, LV_PART_MAIN);
    lv_obj_set_style_text_color(ui_LabelSpeedMiniGear, ui_theme_color_lv(UI_COLOR_TEXT_SECONDARY), LV_PART_MAIN);
    lv_obj_align(ui_LabelSpeedMiniGear, LV_ALIGN_CENTER, -72, 126);

    ui_LabelSpeedMiniRpm = lv_label_create(ui_ScreenPageSpeed);
    lv_label_set_text(ui_LabelSpeedMiniRpm, "RPM ----");
    lv_obj_set_width(ui_LabelSpeedMiniRpm, 142);
    lv_obj_set_style_text_align(ui_LabelSpeedMiniRpm, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_LabelSpeedMiniRpm, &ui_font_FontTypoderSize16, LV_PART_MAIN);
    lv_obj_set_style_text_color(ui_LabelSpeedMiniRpm, ui_theme_color_lv(UI_COLOR_TEXT_SECONDARY), LV_PART_MAIN);
    lv_obj_align(ui_LabelSpeedMiniRpm, LV_ALIGN_CENTER, 72, 126);

    ui_ImageSpeedBlackEar = lv_img_create(ui_ScreenPageSpeed);
    lv_img_set_src(ui_ImageSpeedBlackEar, &ui_img_pngblackear_png);
    lv_obj_set_width(ui_ImageSpeedBlackEar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSpeedBlackEar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageSpeedBlackEar, 0);
    lv_obj_set_y(ui_ImageSpeedBlackEar, -142);
    lv_obj_set_align(ui_ImageSpeedBlackEar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSpeedBlackEar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSpeedBlackEar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_nav_attach_gesture(ui_SpeedPageArcSpeedBack, UI_NAV_PAGE_SPEED);
    ui_nav_attach_gesture(ui_ScreenPageSpeed, UI_NAV_PAGE_SPEED);

}
