// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ
// Modified: EasterEgg page replaced with Device Info page

#include "../ui.h"
#include "bsp_obd_dsp/nvs_storage.h"
#include "bsp_obd_dsp/elm327_ble_client.h"
#include "bsp_obd_dsp/espnow_link.h"

#ifndef OBD_GAUGE_BUILD_TAG
#define OBD_GAUGE_BUILD_TAG "unknown"
#endif

void ui_ScreenPageEasterEgg_screen_init(void)
{
    ui_ScreenPageEasterEgg = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPageEasterEgg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenPageEasterEgg, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_helpers_style_screen_bg(ui_ScreenPageEasterEgg);
    lv_obj_set_style_bg_opa(ui_ScreenPageEasterEgg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Keep the Sky Gauge page to five concise lines of device information. */
    // Role + connection state: master/standalone show BLE (ELM327), slave shows its master
    uint8_t device_role = nvs_cfg_get()->device_role;
    bool is_slave = (device_role == ESPNOW_ROLE_SLAVE);
    const char *mode_str = is_slave ? "从机"
                         : (device_role == ESPNOW_ROLE_MASTER) ? "主机" : "独立";
    const char *conn_name, *conn_status;
    if (is_slave) {
        bool linked = espnow_link_slave_has_data();
        const char *mname = espnow_link_get_master_name();
        conn_name   = (linked && mname[0]) ? mname : "--";
        conn_status = linked ? "已连接" : "等待";
    } else {
        const char *ble_name = elm327_ble_get_connected_name();
        if (!ble_name || ble_name[0] == '\0') ble_name = "Not set";
        conn_name   = ble_name;
        conn_status = elm327_ble_is_connected() ? "已连接" : "未连接";
    }

    ui_LabelEasterEggInfo = lv_label_create(ui_ScreenPageEasterEgg);
    lv_label_set_long_mode(ui_LabelEasterEggInfo, LV_LABEL_LONG_WRAP);
    lv_obj_set_width(ui_LabelEasterEggInfo, 280);
    lv_label_set_text_fmt(ui_LabelEasterEggInfo,
        "模式: %s\n"
        "连接: %s\n"
        "状态: %s\n"
        "电压: --.- V\n"
        "电量: --%%\n"
        "固件: %s",
        mode_str, conn_name, conn_status, OBD_GAUGE_BUILD_TAG);
    lv_obj_set_style_text_font(ui_LabelEasterEggInfo, &ui_font_Chinese16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelEasterEggInfo, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelEasterEggInfo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelEasterEggInfo, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_align(ui_LabelEasterEggInfo, LV_ALIGN_CENTER, 0, 0);

    imageEasterEgg = NULL;

    // Gesture event on screen for page navigation
    ui_nav_attach_gesture(ui_ScreenPageEasterEgg, UI_NAV_PAGE_SKY_GAUGE);
    lv_obj_add_event_cb(ui_ScreenPageEasterEgg, ui_event_easter_egg_background,
                        LV_EVENT_CLICKED, NULL);
}
