// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ
// The UI theme is named PINK_CAT (pink cat): main color pink, secondary color purple
#include "ui.h"
#include "ui_helpers.h"
#include "ui_ext.h"
#include "ui_disp_item.h"
#include "ui_theme.h"
#include "theme_engine/theme_interface.h"
#include "app_obd_dsp/app_event.h"
#include "app_obd_dsp/obd_data_cache.h"
#include "app_obd_dsp/obd_tpms_cache.h"
#include "app_media/media_alert.h"
#include <driver/gpio.h>
#include "bsp_obd_dsp/bsp_board.h"
#include "bsp_obd_dsp/nvs_storage.h"
#include "bsp_obd_dsp/lcd_driver/ST77916.h"
#include "bsp_obd_dsp/elm327_ble_client.h"
#include "bsp_obd_dsp/esp_battery.h"
#include "bsp_obd_dsp/espnow_link.h"
#include "bsp_obd_dsp/gauge_pair_ble_client.h"
#include "bsp_obd_dsp/racechrono_ble_diy.h"
#include "app_obd_dsp/vehicle_profiles.h"
#include "app_obd_dsp/boot_block_player.h"
#include "app_obd_dsp/boot_media_mount.h"
#include "app_obd_dsp/ota_wifi_server.h"
#include "esp_system.h"
#include "esp_random.h"
#include "esp_log.h"
#include "esp_idf_version.h"
#include "esp_timer.h"
#include <stdio.h>
#include <stdint.h>
#include <string.h>


static const char *TAG = "ui";
static void ui_nav_ble_leave(void);

///////////////////// VARIABLES ////////////////////
void ui_ScreenPageLogo_screen_init(void);
lv_obj_t * ui_ScreenPageLogo;
lv_obj_t * imageLogo;
lv_obj_t * imageEasterEgg;

// SCREEN: ui_ScreenPageMain
void ui_ScreenPageMain_screen_init(void);
lv_obj_t * ui_ScreenPageMain;
lv_obj_t * ui_ImageMainPageback;
lv_obj_t * ui_SpinnerMainPage;
lv_obj_t * ui_ArcGearNumBack;
lv_obj_t * ui_LabelGeningRpmText;
lv_obj_t * ui_LabelGeningRpmUnitText;
lv_obj_t * ui_LabelCarSpeedText;
lv_obj_t * ui_LabelCarSpeedUnitText;
lv_obj_t * ui_ContainerMainPageBottomBlock;
lv_obj_t * ui_LabelGearNumText;
lv_obj_t * ui_ContainerMainPageMlieageBlock;
lv_obj_t * ui_LabelMainMlieageText;
lv_obj_t * ui_LabelMainMieageNum;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenPageGear
void ui_ScreenPageGear_screen_init(void);
lv_obj_t * ui_ScreenPageGear;
lv_obj_t * ui_GearPageArcGearNumBack;
lv_obj_t * ui_GearPageArcLabelGearNumText;
lv_obj_t * ui_ImageGearBlackEar;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenPageThemeGauge (theme-partition custom gauge page; only
// reachable if the active theme declares a "main_gauge" theme page — see
// theme_engine/theme_interface.h. Not SquareLine-generated, hand-written below.)
void ui_ScreenPageThemeGauge_screen_init(void);
lv_obj_t * ui_ScreenPageThemeGauge;
uint8_t ui_theme_gauge_page_index = 0;  // Current theme page index

// SCREEN: ui_ScreenPageRpm
void ui_ScreenPageRpm_screen_init(void);
lv_obj_t * ui_ScreenPageRpm;
lv_obj_t * ui_RpmPageArcRpmBack;
lv_obj_t * ui_RpmPageArcLabelRpmText;
lv_obj_t * ui_RpmPageArcLabelRpmUnit;
lv_obj_t * ui_ImageRpmBlackEar;
lv_obj_t * ui_LabelRpmTitle;
lv_obj_t * ui_LabelRpmMiniTemp;
lv_obj_t * ui_LabelRpmMiniVoltage;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenPageSpeed
void ui_ScreenPageSpeed_screen_init(void);
lv_obj_t * ui_ScreenPageSpeed;
lv_obj_t * ui_SpeedPageArcSpeedBack;
lv_obj_t * ui_SpeedPageArcLabelSpeedText;
lv_obj_t * ui_SpeedPageArcLabelSpeedUnit;
lv_obj_t * ui_ImageSpeedBlackEar;
lv_obj_t * ui_LabelSpeedTitle;
lv_obj_t * ui_LabelSpeedMiniGear;
lv_obj_t * ui_LabelSpeedMiniRpm;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenPageEasterEgg
void ui_ScreenPageEasterEgg_screen_init(void);
lv_obj_t * ui_ScreenPageEasterEgg;
lv_obj_t * ui_SpinnerEasterEgg;
lv_obj_t * ArcPageEasterEggBack;
lv_obj_t * ui_ImageEggBlackEar;
lv_obj_t * ui_LabelEasterEggInfo;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageBLEScan
void ui_ScreenPageBLEScan_screen_init(void);
lv_obj_t * ui_ScreenPageBLEScan;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageOTAMode
void ui_ScreenPageOTAMode_screen_init(void);
void ui_ota_mode_refresh(void);

// SCREEN: ui_ScreenPageTemp
void ui_ScreenPageTemp_screen_init(void);
lv_obj_t * ui_ScreenPageTemp;

// SCREEN: ui_ScreenPageTpms
void ui_ScreenPageTpms_screen_init(void);
lv_obj_t * ui_ScreenPageTpms;
void ui_ScreenPageTpmsConfig_screen_init(void);
extern lv_obj_t * ui_ScreenPageTpmsConfig;

// SCREEN: ui_ScreenPageTempCustom
void ui_ScreenPageTempCustom_screen_init(void);
lv_obj_t * ui_ScreenPageTempCustom;

// SCREEN: ui_ScreenPageOilPressure
void ui_ScreenPageOilPressure_screen_init(void);
lv_obj_t * ui_ScreenPageOilPressure;

// SCREEN: ui_ScreenPageInfo
void ui_ScreenPageInfo_screen_init(void);
extern lv_obj_t * ui_ScreenPageInfo;
extern lv_obj_t * ui_LabelInfoFuel;
extern lv_obj_t * ui_LabelInfoFuelNeed;

// SCREEN: ui_ScreenPageInfoCustom
void ui_ScreenPageInfoCustom_screen_init(void);
lv_obj_t * ui_ScreenPageInfoCustom;
// labels defined in ui_ScreenPageInfo.c
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageSettings
void ui_ScreenPageSettings_screen_init(void);
lv_obj_t * ui_ScreenPageSettings;
void ui_ScreenPageAlertMedia_screen_init(void);
lv_obj_t * ui_ScreenPageAlertMedia;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageOilWarn
void ui_ScreenPageOilWarn_screen_init(void);
lv_obj_t * ui_ScreenPageOilWarn;
void ui_ScreenPageRpmWarn_screen_init(void);
lv_obj_t * ui_ScreenPageRpmWarn;
void ui_ScreenPageSpeedConfig_screen_init(void);
lv_obj_t * ui_ScreenPageSpeedConfig;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageNeedle (needle-style configurable gauge)
void ui_ScreenPageNeedle_screen_init(void);
lv_obj_t * ui_ScreenPageNeedle;
lv_meter_scale_t * ui_NeedleScale;
lv_meter_indicator_t * ui_NeedleIndic;
lv_obj_t * ui_NeedleMeter;
lv_obj_t * ui_NeedleValueLabel;
lv_obj_t * ui_NeedleNameLabel;
lv_obj_t * ui_NeedleUnitLabel;
lv_obj_t * ui_NeedleArc;
lv_obj_t * ui_NeedleSourceLabel;
// SCREEN: ui_ScreenPageNeedleConfig
void ui_ScreenPageNeedleConfig_screen_init(void);
lv_obj_t * ui_ScreenPageNeedleConfig;

// SCREEN: ui_ScreenPageMultiGauge (triple-gauge settings: master/slave + master selection)
void ui_ScreenPageMultiGauge_screen_init(void);
lv_obj_t * ui_ScreenPageMultiGauge;
lv_obj_t * ui_LabelMultiValue[3];
lv_obj_t * ui_LabelMultiRole;

// SCREEN: ui_ScreenPageChartConfig (chart data-source selection)
void ui_ScreenPageChartConfig_screen_init(void);
lv_obj_t * ui_ScreenPageChartConfig;

// SCREEN: ui_ScreenPageChartAlarm (chart alarm threshold settings)
void ui_ScreenPageChartAlarm_screen_init(void);
lv_obj_t * ui_ScreenPageChartAlarm;

// SCREEN: ui_ScreenPageIntro (triple-gauge boot animation RACE/AS/ONE)
void ui_ScreenPageIntro_screen_init(void);
lv_obj_t * ui_ScreenPageIntro;

// SCREEN: ui_ScreenPageODBProtocal
void ui_ScreenPageODBProtocal_screen_init(void);
lv_obj_t * ui_ScreenPageODBProtocal;
lv_obj_t * ui_ArcPageODBProtocalBack;
lv_obj_t * ui_RollerODBProtocalChoose;
lv_obj_t * ui_ImageODBProtocalBlackEar;
lv_obj_t * ui_LabelOBDIIText;
lv_obj_t * ui_LabelSureTipText;

// EVENTS
lv_obj_t * ui____initial_actions0;


static uint16_t usSaveProtTimeCnt = 0; //OBD protocol save timer

// IMAGES AND IMAGE SETS
#define SAVE_PROTOCOL_TIME 2000 //long-press duration to save the protocol, ms
 
///////////////////// TEST LVGL SETTINGS ////////////////////
/* ---- Gauge sweep animation ----
   Moved to ui_ext.c; the SWEEP_* constants live in ui_ext.h and the sweep state
   machine is driven via ui_ext_sweep_active()/ui_ext_sweep_get_step()/ui_ext_sweep_tick(). */
#define OIL_PRESS_TREND_POINTS 30
#define OIL_PRESS_TREND_SAMPLE_MS 1000

/* ---- Digit-ramp animation thresholds (used by disp_item_update) ---- */
#define ANIM_THRESH_RPM   50   // RPM diff ≤50 steps by ±1
#define ANIM_THRESH_SPD   10   // speed diff ≤10 steps by ±1
#define ANIM_THRESH_TEMP   5   // temperature diff ≤5 steps by ±1

// Adaptive step: diff ≤ threshold steps by ±1, diff > threshold approaches proportionally
// The RPM/Speed pages must update label + arc together, which differs from disp_item_update, so a local copy is kept
static inline int32_t anim_step_i32(int32_t displayed, int32_t target, int32_t threshold)
{
    int32_t diff = target - displayed;
    if (diff == 0) return displayed;
    int32_t abs_diff = (diff > 0) ? diff : -diff;
    int32_t step = (diff > 0) ? 1 : -1;

    if (abs_diff > threshold) {
        int32_t rapid = abs_diff / 2;     // eat ~50% of the gap per tick (was 33%, faster convergence)
        if (rapid < 2) rapid = 2;          // minimum 2 steps
        if (rapid > abs_diff) rapid = abs_diff;
        step = (diff > 0) ? rapid : -rapid;
    }
    return displayed + step;
}

// RPM warning flash (test ticks, strobe, linked ramp) migrated to ui_ext.c — see ui_ext_rpm_flash_tick()

// LVGL task handle (set by app_main); priority is temporarily raised to own the CPU while flashing
TaskHandle_t g_lvgl_task_handle = NULL;

// ===== Showroom mode / boot-video state =====
// Moved to ui_ext.c (see ui_ext_showroom_* / ui_ext_boot_video_tick / ui_ext_intro_tick).

// (showroom_load_slot / boot_video_timer_cb moved to ui_ext.c)

// (ui_sweep_get_step / ui_showroom_* / ui_intro_* accessors moved to ui_ext.c)
static int16_t s_oil_pressure_trend[OIL_PRESS_TREND_POINTS];
static bool s_oil_pressure_trend_ready = false;
static uint32_t s_oil_pressure_trend_tick = 0;
// Generic chart page: invalid-sample sentinel (distinct from legit negative values like coolant temp -10) + raw-value range of the current data item (clamping/Y-axis on refresh)
// CHART_INVALID has moved to ui_disp_item.h
static int32_t s_chart_ymin = 0;
static int32_t s_chart_ymax = 100;

// The disp_item system has moved to ui_disp_item.c/h

static uint8_t needle_active_source(void)
{
    uint8_t src = nvs_cfg_get()->needle_source_idx;
    if (src >= DISP_ITEM_COUNT) src = DISP_ITEM_CLT;
    return src;
}

static void ui_temp_update_arc(disp_item_t item, int32_t raw_value, bool valid)
{
    if (!ui_TempArc) return;
    if (!valid) {
        lv_arc_set_value(ui_TempArc, 0);
        return;
    }

    int32_t nmin, nmax, div;
    ui_disp_item_range((uint8_t)item, &nmin, &nmax, &div);
    if (div <= 0 || nmax <= nmin) return;

    int64_t raw_min = (int64_t)nmin * div;
    int64_t raw_max = (int64_t)nmax * div;
    int64_t progress = ((int64_t)raw_value - raw_min) * 100 / (raw_max - raw_min);
    if (progress < 0) progress = 0;
    if (progress > 100) progress = 100;
    lv_arc_set_value(ui_TempArc, (int16_t)progress);
}

void ui_needle_apply_source(void)
{
    if (!ui_NeedleMeter || !ui_NeedleScale) return;
    uint8_t src = needle_active_source();
    const needle_scale_meta_t *ns = &s_needle_scale_meta[src];
    // 270° sweep, start angle 135° (gap centered at the bottom), matching classic mechanical gauges
    lv_meter_set_scale_range(ui_NeedleMeter, ui_NeedleScale, ns->nmin, ns->nmax, 270, 135);
    lv_meter_set_indicator_value(ui_NeedleMeter, ui_NeedleIndic, ns->nmin);
    if (ui_NeedleArc) lv_arc_set_value(ui_NeedleArc, 0);
    if (ui_NeedleNameLabel) lv_label_set_text(ui_NeedleNameLabel, s_disp_meta[src].name);
    if (ui_NeedleUnitLabel) lv_label_set_text(ui_NeedleUnitLabel, s_disp_meta[src].unit);
    if (ui_NeedleSourceLabel) lv_label_set_text_fmt(ui_NeedleSourceLabel, "SOURCE  %s", s_disp_meta[src].name);
}

void ui_needle_page_update(float sweep_ratio, int16_t clt, int16_t iat, int16_t oil,
                           int16_t load_pct, int16_t tps, int32_t bat_mv,
                           int16_t oilp_x10, int16_t brake_x10,
                           uint16_t rpm, uint16_t speed, int16_t boost_x10,
                           int16_t afr_x100)
{
    if (!ui_ScreenPageNeedle || !ui_NeedleMeter || !ui_NeedleIndic) return;
    uint8_t src = needle_active_source();
    const needle_scale_meta_t *ns = &s_needle_scale_meta[src];
    static int32_t s_last_needle_meter = INT32_MIN;

    // Sweep self-test after connecting: the needle sweeps the full range nmin→nmax→nmin
    if (sweep_ratio >= 0.0f) {
        if (sweep_ratio > 1.0f) sweep_ratio = 1.0f;
        int32_t nval = ns->nmin + (int32_t)((float)(ns->nmax - ns->nmin) * sweep_ratio);
        if (nval != s_last_needle_meter) {
            lv_meter_set_indicator_value(ui_NeedleMeter, ui_NeedleIndic, nval);
            s_last_needle_meter = nval;
        }
        if (ui_NeedleArc) lv_arc_set_value(ui_NeedleArc, (int16_t)((int64_t)(nval - ns->nmin) * 100 / (ns->nmax - ns->nmin)));
        disp_item_set_text(ui_NeedleValueLabel, src, nval * ns->div, true);
        return;
    }

    int32_t raw = 0;
    bool valid = disp_item_read_value(src, clt, iat, oil, load_pct, tps, bat_mv,
                                      oilp_x10, brake_x10, rpm, speed, boost_x10, afr_x100, &raw);

    static int32_t s_disp_needle = 0;
    static uint8_t s_last_needle_src = 0xFF;
    if (s_last_needle_src != src) {
        s_last_needle_src = src;
        s_disp_needle = 0;  // reset on source switch, avoiding a ramp from the old source's value
    }
    /* Threshold = 3% of range: small ranges (temps) smooth by ±1, large ranges (RPM) approach proportionally */
    int32_t needle_thresh = (ns->nmax - ns->nmin) / 30;
    if (needle_thresh < 2) needle_thresh = 2;

    disp_item_update(&s_disp_needle, ui_NeedleValueLabel, src, raw, valid, needle_thresh);

    // Needle position: use the smoothed value
    int32_t nval = (s_disp_needle / ns->div);
    if (nval < ns->nmin) nval = ns->nmin;
    if (nval > ns->nmax) nval = ns->nmax;
    if (nval != s_last_needle_meter) {
        lv_meter_set_indicator_value(ui_NeedleMeter, ui_NeedleIndic, nval);
        s_last_needle_meter = nval;
    }
    if (ui_NeedleArc) {
        int32_t percent = (int32_t)((int64_t)(nval - ns->nmin) * 100 / (ns->nmax - ns->nmin));
        if (percent < 0) percent = 0;
        if (percent > 100) percent = 100;
        lv_arc_set_value(ui_NeedleArc, (int16_t)percent);
    }
}

static void oil_pressure_trend_init(void)
{
    if (s_oil_pressure_trend_ready) return;

    for (uint32_t i = 0; i < OIL_PRESS_TREND_POINTS; ++i) {
        s_oil_pressure_trend[i] = CHART_INVALID;
    }

    s_oil_pressure_trend_ready = true;
}

static void oil_pressure_trend_push(int16_t sample_x10)
{
    oil_pressure_trend_init();

    for (uint32_t i = 0; i < OIL_PRESS_TREND_POINTS - 1; ++i) {
        s_oil_pressure_trend[i] = s_oil_pressure_trend[i + 1];
    }
    s_oil_pressure_trend[OIL_PRESS_TREND_POINTS - 1] = sample_x10;
}

// Generic chart refresh: Y range = s_chart_ymin..s_chart_ymax (set per data item by ui_chart_apply_source);
// invalid samples (CHART_INVALID) keep the last valid value; legit negative values (e.g. coolant temp) are supported.
static void oil_pressure_chart_refresh(void)
{
    if (!ui_ChartOilPressure || !ui_OilPressureChartSeries) return;

    int32_t last_valid = s_chart_ymin;
    bool has_last = false;

    lv_chart_set_range(ui_ChartOilPressure, LV_CHART_AXIS_PRIMARY_Y, s_chart_ymin, s_chart_ymax);

    for (uint32_t i = 0; i < OIL_PRESS_TREND_POINTS; ++i) {
        int16_t sample = s_oil_pressure_trend[i];
        int32_t v;

        if (sample != CHART_INVALID) {
            last_valid = sample;
            has_last = true;
        }

        v = has_last ? last_valid : s_chart_ymin;
        if (v < s_chart_ymin) v = s_chart_ymin;
        if (v > s_chart_ymax) v = s_chart_ymax;

        lv_chart_set_value_by_id(ui_ChartOilPressure, ui_OilPressureChartSeries, i, v);
    }

    lv_chart_refresh(ui_ChartOilPressure);
}

// Apply the chart page title/dot/unit/color/Y-range per chart_source_idx (call after the data source changes)
void ui_chart_apply_source(void)
{
    uint8_t src = nvs_cfg_get()->chart_source_idx;
    if (src >= DISP_ITEM_COUNT) src = DISP_ITEM_OILP;
    const disp_item_meta_t *m = &s_disp_meta[src];
    const needle_scale_meta_t *ns = &s_needle_scale_meta[src];
    s_chart_ymin = ns->nmin * ns->div;   // raw-value range (matches the raw values fed to the chart)
    s_chart_ymax = ns->nmax * ns->div;
    if (ui_LabelChartTitle) {
        lv_label_set_text(ui_LabelChartTitle, m->name);
        lv_obj_set_style_text_color(ui_LabelChartTitle, lv_color_hex(m->color), LV_PART_MAIN);
    }
    if (ui_ChartDot) lv_obj_set_style_bg_color(ui_ChartDot, lv_color_hex(m->color), LV_PART_MAIN);
    if (ui_LabelChartUnit) lv_label_set_text(ui_LabelChartUnit, m->unit);
    if (ui_ChartOilPressure) {
        lv_obj_set_style_line_color(ui_ChartOilPressure, lv_color_hex(m->color), LV_PART_ITEMS);
        // the line actually uses the series' own color (overrides the ITEMS style); the series color must be changed directly for it to take effect
        if (ui_OilPressureChartSeries) ui_OilPressureChartSeries->color = lv_color_hex(m->color);
        lv_chart_set_range(ui_ChartOilPressure, LV_CHART_AXIS_PRIMARY_Y, s_chart_ymin, s_chart_ymax);
        lv_chart_refresh(ui_ChartOilPressure);
    }
    // reset the trend buffer so no stale curve remains after switching data source
    s_oil_pressure_trend_ready = false;
    s_oil_pressure_trend_tick = 0;
}

// ===== Boot flow state / "NO SIGNAL" overlay =====
// (boot_goto_ble_scan / boot_enter_default_page / update_no_signal_overlay moved to ui_ext.c)

static void ui_update_metric_header(lv_obj_t *name_label,
                                    lv_obj_t *unit_label,
                                    lv_obj_t *dot_label,
                                    disp_item_t item)
{
    lv_color_t color = lv_color_hex(s_disp_meta[item].color);

    if (name_label) {
        lv_label_set_text(name_label, s_disp_meta[item].name);
        lv_obj_set_style_text_color(name_label, color, LV_PART_MAIN);
    }
    if (unit_label) {
        lv_label_set_text(unit_label, s_disp_meta[item].unit);
    }
    if (dot_label) {
        lv_obj_set_style_bg_color(dot_label, color, LV_PART_MAIN);
    }
}

static uint32_t ui_refresh_period_ms_for_screen(lv_obj_t *scr,
                                                bool in_sweep,
                                                bool rpm_flashing,
                                                bool rpm_link_ramp)
{
    if (in_sweep) {
        return SWEEP_TICK_MS;
    }
    if (rpm_flashing) {
        return RPM_FLASH_PERIOD_MS;
    }
    if (rpm_link_ramp) {
        return 16;
    }

    if (scr == ui_ScreenPageGear || scr == ui_ScreenPageRpm ||
        scr == ui_ScreenPageSpeed || scr == ui_ScreenPageNeedle ||
        scr == ui_ScreenPageThemeGauge) {
        return 16;
    }
    if (scr == ui_ScreenPageTemp || scr == ui_ScreenPageTpms || scr == ui_ScreenPageInfo ||
        scr == ui_ScreenPageOilPressure || scr == ui_ScreenPageLogo ||
        scr == ui_ScreenPageIntro) {
        return 33;
    }
    if (scr == ui_ScreenPageSettings || scr == ui_ScreenPageMultiGauge ||
        scr == ui_ScreenPageBLEScan || scr == ui_ScreenPageOTAMode || scr == ui_ScreenPageODBProtocal ||
        scr == ui_ScreenPageTempCustom || scr == ui_ScreenPageInfoCustom ||
        scr == ui_ScreenPageNeedleConfig || scr == ui_ScreenPageChartConfig ||
        scr == ui_ScreenPageChartAlarm || scr == ui_ScreenPageOilWarn ||
        scr == ui_ScreenPageRpmWarn || scr == ui_ScreenPageEasterEgg ||
        scr == ui_ScreenPageTpmsConfig || scr == ui_ScreenPageSpeedConfig) {
        return 200;
    }
    return 50;
}

static bool ui_screen_updates_live_data(lv_obj_t *scr)
{
    return scr == ui_ScreenPageGear || scr == ui_ScreenPageRpm ||
           scr == ui_ScreenPageSpeed || scr == ui_ScreenPageNeedle ||
           scr == ui_ScreenPageTemp || scr == ui_ScreenPageTpms || scr == ui_ScreenPageOilPressure ||
           scr == ui_ScreenPageInfo || scr == ui_ScreenPageThemeGauge;
}

// Converts the core firmware's live OBD snapshot into the ABI-stable struct
// theme_engine consumes, applying the unit conversions the two structs don't
// share (boost 0.1bar->0.01bar, oil pressure bar->PSI, battery mV->0.1V) and
// clamping into the narrower target field widths. Invalid-sentinel fields are
// passed through as 0 rather than propagating e.g. -32768 into a uint8_t.
static void ui_build_theme_snapshot(obd_snapshot_t *out,
                                     int16_t clt, int16_t oil, int16_t oilp_x10,
                                     int32_t bat_mv, int16_t boost_x10, int16_t afr_x100,
                                     uint16_t usRpm, uint16_t ucSpeed, int16_t tps,
                                     enGear eGear, bool gear_unknown)
{
    memset(out, 0, sizeof(*out));
    out->rpm = usRpm;
    out->speed = (ucSpeed > 255) ? 255 : (uint8_t)ucSpeed;
    out->boost = (boost_x10 <= -32768) ? 0 : (int16_t)(boost_x10 * 10);
    out->coolant_temp = (clt < 0) ? 0 : (clt > 255 ? 255 : (uint8_t)clt);
    if (oilp_x10 < 0) {
        out->oil_pressure = 0;
    } else {
        int32_t psi = (int32_t)(oilp_x10 * 1.45038f / 10.0f + 0.5f);
        out->oil_pressure = (psi > 255) ? 255 : (uint8_t)psi;
    }
    out->gear = gear_unknown ? (int8_t)127 : (int8_t)eGear;
    if (bat_mv < 0) {
        out->battery_voltage = 0;
    } else {
        int32_t dv = bat_mv / 100;
        out->battery_voltage = (dv > 255) ? 255 : (uint8_t)dv;
    }
    out->oil_temp = (oil < 0) ? 0 : (oil > 255 ? 255 : (uint8_t)oil);
    out->afr = (afr_x100 < 0) ? 0 : (uint16_t)afr_x100;
    out->throttle = (tps < 0) ? 0 : (tps > 100 ? 100 : (uint8_t)tps);

    int16_t iat = obd_data_get_intake_temp();
    out->intake_temp = (iat < 0) ? 0 : (iat > 255 ? 255 : (uint8_t)iat);
}

void my_timerMain(lv_timer_t * timer)
{
    // ---- Process the event queue (ESP-NOW / BLE cross-task events) ----
    {
        app_event_t evt;
        while (app_event_recv(&evt)) {
            switch (evt.type) {
                case APP_EVT_ESPNOW_SYNC_SLOT:
                    ui_showroom_set_page_from_sync((int)evt.data.u8);
                    break;
                case APP_EVT_ESPNOW_INTRO_STEP:
                    ui_intro_set_step((int)evt.data.u8);
                    break;
                case APP_EVT_ESPNOW_ENTER_SHOWROOM:
                    ui_showroom_set_active(true);
                    break;
                case APP_EVT_ESPNOW_THRESH_SYNC:
                    // RPM threshold synced from another gauge: write local NVS (the master forwards it to the other slaves) + refresh this page
                    espnow_link_apply_synced_threshold((uint16_t)evt.data.u16);
                    ui_rpm_warn_refresh_from_nvs();
                    break;
                default:
                    break;
            }
        }
    }

    static uint16_t usRpm = 0;
    static uint16_t ucSpeed = 0;  // uint16_t so sweep can reach 999
    static enGear eGear = GEAR_NEUTRAL;
    static bool  s_gear_unknown = false;   // OBD-gear profile can't read a valid gear → show "--" (no ratio-calc fallback)
    // rpm flash state (red/black toggle, strobing flag, linked ramp) moved to ui_ext.c
    // Sweep animation detection (excludes showroom sync values 200+); sweep state lives in ui_ext.c now
    #define IN_SWEEP (ui_ext_sweep_active())
    static uint8_t ucOnlyOnce = 0;
    static uint32_t ulOpenLightTimeCnt = 0;

    const nvs_user_cfg_t *user_cfg = nvs_cfg_get();
    int16_t clt = 0;
    int16_t iat = 0;
    int16_t oil = 0;
    int16_t oilp_x10 = 0;
    int16_t brake_x10 = 0;
    int16_t load_pct = 0;
    int16_t tps = 0;
    int32_t bat_mv = 0;
    int32_t esp_bat_mv = -1;
    int esp_bat_pct = -1;
    int16_t boost_x10 = 0;
    int16_t afr_x100 = 0;
    int16_t fuel_pct = -1;

    esp_battery_get_snapshot(&esp_bat_mv, &esp_bat_pct);

    /* ---- Sweep trigger ----
       Master: triggered the instant the ELM327 BLE connects and advances the animation itself;
       Slave: never self-triggers, driven by the master's broadcast sweep_step (espnow recv → app_event queue). */
    bool is_slave = (user_cfg->device_role == ESPNOW_ROLE_SLAVE);
    // "connected" signal: slave=master data being received, master=ELM327 BLE connected (shared by status display and the master's sweep trigger)
    bool ble_now = is_slave ? espnow_link_slave_has_data() : elm327_ble_is_connected();
    ui_ext_sweep_trigger(ble_now, is_slave);
    /* ---- Showroom mode: master drives slots, slaves follow (moved to ui_ext.c) ---- */
    ui_ext_showroom_tick(is_slave);

    lv_obj_t *scr = lv_scr_act();
    bool live_data_screen = ui_screen_updates_live_data(scr);
    bool rpm_warn_possible = ui_ext_rpm_warn_possible();

    if (!IN_SWEEP && (live_data_screen || rpm_warn_possible || ui_ext_rpm_is_flashing() || ui_ext_rpm_link_ramp_active())) {
        obd_data_snapshot_t obd;

        obd_data_get_snapshot(&obd);
        clt       = obd.coolant_temp;
        iat       = obd.intake_temp;
        oil       = obd.oil_temp;      // real oil temperature °C (SSM 22 10 17), -100=invalid
        oilp_x10  = obd.oil_pressure_x10; // oil pressure 0.1bar, -1=invalid
        brake_x10 = obd.brake_temp_x10; // brake temperature 0.1°C
        load_pct  = obd.load_pct;      // engine load 0~100%, -1=invalid
        tps       = obd.tps;
        bat_mv    = obd.bat_mv;
        boost_x10 = obd.boost_x10; // boost gauge pressure 0.1bar, -32768=invalid
        afr_x100  = obd.afr_x100;   // air-fuel ratio ×100, -1=invalid
        fuel_pct  = obd.fuel_pct;
        usRpm     = obd.rpm;
        ucSpeed   = obd.speed;
        int8_t decoded_gear = obd.gear;
        if (decoded_gear >= 0 && decoded_gear <= GEAR_8) {
            eGear = (enGear)decoded_gear;
            s_gear_unknown = false;
        } else if (vehicle_profile_get_active()->obd_gear_did != 0) {
            // OBD gear profile: no RPM/speed ratio fallback — show "--" until a valid gear arrives
            s_gear_unknown = true;
        } else {
            eGear = calculate_gear(usRpm, ucSpeed);
            s_gear_unknown = false;
        }
    }

    /* Media alerts are queued without blocking the LVGL task. The WAV service
       applies its own duplicate suppression, so these checks can run at the
       same cadence as the existing gauge refresh. */
    if (!IN_SWEEP) {
        if (bat_mv > 0 && bat_mv < (int32_t)user_cfg->tpms_voltage_min_mv) {
            (void)media_alert_notify(MEDIA_ALERT_VOLTAGE);
        }
        if (clt > 110) {
            (void)media_alert_notify(MEDIA_ALERT_TEMP_HIGH);
        }
        obd_tpms_snapshot_t tpms_alert;
        obd_tpms_cache_expire(esp_timer_get_time(), 4000000);
        obd_tpms_cache_get_snapshot(&tpms_alert);
        for (uint8_t i = 0; i < OBD_TPMS_WHEEL_COUNT; ++i) {
            if (tpms_alert.valid[i] &&
                (tpms_alert.pressure_bar_x100[i] < (int16_t)user_cfg->tpms_pressure_min_bar_x100 ||
                 tpms_alert.pressure_bar_x100[i] > (int16_t)user_cfg->tpms_pressure_max_bar_x100)) {
                (void)media_alert_notify(MEDIA_ALERT_TPMS);
                break;
            }
        }
    }

    /* ---- Data source: sweep or real OBD (sweep state machine moved to ui_ext.c) ---- */
    float sweep_ratio = ui_ext_sweep_tick(is_slave, user_cfg->brightness_day);
    if (sweep_ratio >= 0.0f) {
        usRpm   = (uint16_t)(SWEEP_RPM_PEAK * sweep_ratio);
        ucSpeed = (uint16_t)(SWEEP_SPEED_PEAK * sweep_ratio); // uint16_t so it can hold 999
        eGear   = (enGear)((int)(6.0f * sweep_ratio + 0.5f)); // up to 6th gear
        s_gear_unknown = false;
        // Temp/Info/Chart pages animate their own data item via disp_item_sweep_value();
        // the theme-gauge page (ui_build_theme_snapshot below) has no such per-item logic
        // and just forwards these locals as-is, so without this they'd stay frozen at the
        // 0 they were declared with above (real OBD reads are skipped while IN_SWEEP).
        clt       = (int16_t)disp_item_sweep_value(DISP_ITEM_CLT, sweep_ratio);
        oil       = (int16_t)disp_item_sweep_value(DISP_ITEM_OIL, sweep_ratio);
        oilp_x10  = (int16_t)disp_item_sweep_value(DISP_ITEM_OILP, sweep_ratio);
        bat_mv    = disp_item_sweep_value(DISP_ITEM_BAT, sweep_ratio);
        boost_x10 = (int16_t)disp_item_sweep_value(DISP_ITEM_BOOST, sweep_ratio);
        afr_x100  = (int16_t)disp_item_sweep_value(DISP_ITEM_AFR, sweep_ratio);
        tps       = (int16_t)disp_item_sweep_value(DISP_ITEM_TPS, sweep_ratio);
    }
    /*Gear page: refresh only while this page is actually shown, no idle background updates*/
    if (scr == ui_ScreenPageGear) {
        static const char *pGearNum[] = {"N","1","2","3","4","5","6","7","8"};
        static enGear s_last_gear_disp = GEAR_NEUTRAL;
        static bool s_last_gear_unknown = false;
        uint8_t gc = vehicle_profile_get_active()->gear_count;
        if (gc < 1) gc = 6;
        enGear g = (eGear <= GEAR_8) ? eGear : GEAR_8;
        if (s_gear_unknown != s_last_gear_unknown || g != s_last_gear_disp || IN_SWEEP) {
            s_last_gear_unknown = s_gear_unknown;
            s_last_gear_disp = g;
            if (s_gear_unknown) {
                // The 140px gear font only contains "0123456789NR"; '-' would render as tofu boxes.
                lv_obj_set_style_text_font(ui_GearPageArcLabelGearNumText, &ui_font_FontTypoderSize56, LV_PART_MAIN | LV_STATE_DEFAULT);
                lv_label_set_text(ui_GearPageArcLabelGearNumText, "--");
                lv_arc_set_value(ui_GearPageArcGearNumBack, 0);
            } else {
                lv_obj_set_style_text_font(ui_GearPageArcLabelGearNumText, &ui_font_FontTypoderSize140, LV_PART_MAIN | LV_STATE_DEFAULT);
                lv_label_set_text(ui_GearPageArcLabelGearNumText, pGearNum[g]);
                lv_arc_set_value(ui_GearPageArcGearNumBack, (uint16_t)g * 100 / gc);
            }
        }
    }
    /* Theme-provided gauge page: feed the theme engine's arc/bar/label bindings */
    if (scr == ui_ScreenPageThemeGauge) {
        obd_snapshot_t theme_snap;
        ui_build_theme_snapshot(&theme_snap, clt, oil, oilp_x10, bat_mv, boost_x10, afr_x100,
                                 usRpm, ucSpeed, tps, eGear, s_gear_unknown);
        theme_update_data(&theme_snap);
    }
    /*RPM page: direct output, no animation delay (CAN 100Hz data is already clean)*/
    if (scr == ui_ScreenPageRpm) {
        static int32_t s_last_rpm = -1;
        if ((int32_t)usRpm != s_last_rpm) {
            s_last_rpm = (int32_t)usRpm;
            lv_label_set_text_fmt(ui_RpmPageArcLabelRpmText, "%d", (int)usRpm);
            lv_arc_set_value(ui_RpmPageArcRpmBack, (uint32_t)usRpm*100/SWEEP_RPM_PEAK);
        }
        if (ui_LabelRpmMiniTemp) {
            if (clt > -40) lv_label_set_text_fmt(ui_LabelRpmMiniTemp, "CLT %d'C", (int)clt);
            else lv_label_set_text(ui_LabelRpmMiniTemp, "CLT --'C");
        }
        if (ui_LabelRpmMiniVoltage) {
            if (bat_mv > 0) {
                lv_label_set_text_fmt(ui_LabelRpmMiniVoltage, "BAT %d.%dV",
                                      (int)(bat_mv / 1000), (int)((bat_mv % 1000) / 100));
            } else {
                lv_label_set_text(ui_LabelRpmMiniVoltage, "BAT --.-V");
            }
        }
    }
    /*Speed page: same as above, refresh only while the page is active*/
    if (scr == ui_ScreenPageSpeed) {
        static int32_t s_disp_spd = 0;
        static int32_t s_last_spd = -1;
        static uint16_t s_last_speed_max = 0;
        static lv_obj_t *s_last_speed_screen = NULL;
        if (IN_SWEEP) { s_disp_spd = ucSpeed; }
        else { s_disp_spd = anim_step_i32(s_disp_spd, (int32_t)ucSpeed, ANIM_THRESH_SPD); }
        uint16_t speed_max = user_cfg->speed_max_kmh;
        if (speed_max < NVS_SPEED_MAX_MIN_KMH || speed_max > NVS_SPEED_MAX_MAX_KMH)
            speed_max = NVS_SPEED_MAX_DEFAULT_KMH;
        if (s_disp_spd != s_last_spd || speed_max != s_last_speed_max ||
            scr != s_last_speed_screen) {
            s_last_spd = s_disp_spd;
            s_last_speed_max = speed_max;
            s_last_speed_screen = scr;
            lv_label_set_text_fmt(ui_SpeedPageArcLabelSpeedText, "%d", (int)s_disp_spd);
            ui_speed_arc_set_range(0, speed_max);
            ui_speed_arc_set_value((uint16_t)s_disp_spd);
        }
        if (ui_LabelSpeedMiniRpm) {
            lv_label_set_text_fmt(ui_LabelSpeedMiniRpm, "RPM %d", (int)usRpm);
        }
        if (ui_LabelSpeedMiniGear) {
            static int s_last_speed_gear = -2;
            int gear_value = s_gear_unknown ? -2 : (int)eGear;
            if (gear_value != s_last_speed_gear) {
                s_last_speed_gear = gear_value;
                if (s_gear_unknown) {
                    lv_label_set_text(ui_LabelSpeedMiniGear, "GEAR --");
                } else if (eGear == GEAR_NEUTRAL) {
                    lv_label_set_text(ui_LabelSpeedMiniGear, "GEAR N");
                } else {
                    lv_label_set_text_fmt(ui_LabelSpeedMiniGear, "GEAR %d", gear_value);
                }
            }
        }
    }

    if (scr == ui_ScreenPageMultiGauge && ui_LabelMultiValue[0]) {
        char text[24];
        lv_label_set_text_fmt(ui_LabelMultiValue[0], "%u", (unsigned)usRpm);
        lv_label_set_text_fmt(ui_LabelMultiValue[1], "%u", (unsigned)ucSpeed);
        if (bat_mv > 0) {
            snprintf(text, sizeof(text), "%d.%d", (int)(bat_mv / 1000),
                     (int)((bat_mv % 1000) / 100));
            lv_label_set_text(ui_LabelMultiValue[2], text);
        } else {
            lv_label_set_text(ui_LabelMultiValue[2], "--.-");
        }
        if (ui_LabelMultiRole) {
            const char *role = (user_cfg->device_role == ESPNOW_ROLE_SLAVE) ? "从机" :
                               (user_cfg->device_role == ESPNOW_ROLE_STANDALONE) ? "独立" : "主机";
            lv_label_set_text_fmt(ui_LabelMultiRole, "%s多联表", role);
        }
    }

 /*Needle page (configurable data source, sweeps along during gauge sweep)*/
    if (scr == ui_ScreenPageNeedle) {
        ui_needle_page_update(sweep_ratio, clt, iat, oil, load_pct, tps, bat_mv,
                              oilp_x10, brake_x10, usRpm, ucSpeed, boost_x10, afr_x100);
    }

    /*Temp page*/
    if (scr == ui_ScreenPageTemp && ui_LabelTempValue[0]) {
        static int32_t s_disp_temp[3] = {0};
        static uint8_t s_last_temp_map[3] = {0xFF, 0xFF, 0xFF};

        if(IN_SWEEP) {
            int step = ui_ext_sweep_get_step() - 1; // already incremented
            float r;
            if(step <= SWEEP_STEPS_UP) r = (float)step / (float)SWEEP_STEPS_UP;
            else r = 1.0f;   // hold at max (hold phase)

            for (int i = 0; i < 3; ++i) {
                uint8_t map_idx = user_cfg->temp_display_map[i];
                disp_item_t item = (disp_item_t)(map_idx % DISP_ITEM_COUNT);

                if (s_last_temp_map[i] != map_idx) {
                    s_last_temp_map[i] = map_idx;
                    s_disp_temp[i] = 0;  // reset on source switch, avoiding a ramp from the old source's value
                    ui_update_metric_header(ui_LabelTempName[i], ui_LabelTempUnit[i], ui_LabelTempDot[i], item);
                }

                int32_t sw = disp_item_sweep_value(item, r);
                disp_item_set_text(ui_LabelTempValue[i], item, sw, true);
                disp_item_set_value_color(ui_LabelTempValue[i], item, sw, true);
                if (i == 0) ui_temp_update_arc(item, sw, true);
            }
        } else {
            for (int i = 0; i < 3; ++i) {
                uint8_t map_idx = user_cfg->temp_display_map[i];
                disp_item_t item = (disp_item_t)(map_idx % DISP_ITEM_COUNT);

                if (s_last_temp_map[i] != map_idx) {
                    s_last_temp_map[i] = map_idx;
                    s_disp_temp[i] = 0;  // reset on source switch, avoiding a ramp from the old source's value
                    ui_update_metric_header(ui_LabelTempName[i], ui_LabelTempUnit[i], ui_LabelTempDot[i], item);
                }

                int32_t value = 0;
                bool valid = disp_item_read_value(item, clt, iat, oil, load_pct, tps, bat_mv, oilp_x10, brake_x10, usRpm, ucSpeed, boost_x10, afr_x100, &value);
                disp_item_update(&s_disp_temp[i], ui_LabelTempValue[i], item, value, valid, ANIM_THRESH_TEMP);
                if (i == 0) ui_temp_update_arc(item, s_disp_temp[i], valid);
            }
        }
    }

    /* TPMS page: the four wheel values are maintained by the protocol layer
       and intentionally do not enter obd_data_snapshot_t, preserving the
       legacy UI/ESP-NOW ABI for non-TPMS vehicles. */
    if (scr == ui_ScreenPageTpms && ui_LabelTpmsValue[0]) {
        obd_tpms_snapshot_t tpms;
        obd_data_snapshot_t obd;
        const nvs_user_cfg_t *tpms_cfg = nvs_cfg_get();
        char text[16];
        if (ui_LabelTpmsHeader) {
            lv_label_set_text_fmt(ui_LabelTpmsHeader, "%d.%d-%d.%d bar",
                                  tpms_cfg->tpms_pressure_min_bar_x100 / 100,
                                  (tpms_cfg->tpms_pressure_min_bar_x100 % 100) / 10,
                                  tpms_cfg->tpms_pressure_max_bar_x100 / 100,
                                  (tpms_cfg->tpms_pressure_max_bar_x100 % 100) / 10);
        }
        obd_tpms_cache_expire(esp_timer_get_time(), 4000000);
        obd_tpms_cache_get_snapshot(&tpms);
        obd_data_get_snapshot(&obd);
        for (uint8_t i = 0; i < OBD_TPMS_WHEEL_COUNT; ++i) {
            if (tpms.valid[i]) {
                int16_t pressure = tpms.pressure_bar_x100[i];
                snprintf(text, sizeof(text), "%d.%d", pressure / 100,
                         pressure >= 0 ? (pressure % 100) / 10 : -(pressure % 100) / 10);
            } else {
                snprintf(text, sizeof(text), "--.-");
            }
            if (strcmp(lv_label_get_text(ui_LabelTpmsValue[i]), text) != 0)
                lv_label_set_text(ui_LabelTpmsValue[i], text);
            bool out_of_range = tpms.valid[i] &&
                (tpms.pressure_bar_x100[i] < (int16_t)tpms_cfg->tpms_pressure_min_bar_x100 ||
                 tpms.pressure_bar_x100[i] > (int16_t)tpms_cfg->tpms_pressure_max_bar_x100);
            lv_color_t value_color = out_of_range ? lv_color_hex(0xFF4545) : lv_color_hex(0xFFFFFF);
            lv_obj_set_style_text_color(ui_LabelTpmsValue[i], value_color, LV_PART_MAIN);
            if (ui_TpmsCard[i]) {
                lv_obj_set_style_bg_color(ui_TpmsCard[i],
                    out_of_range ? lv_color_hex(0xFFF1EF) : lv_color_hex(0x0B1F2F), LV_PART_MAIN);
                lv_obj_set_style_border_color(ui_TpmsCard[i],
                    out_of_range ? lv_color_hex(0xFF4545) : lv_color_hex(0x35CFE0), LV_PART_MAIN);
                lv_obj_set_style_shadow_color(ui_TpmsCard[i],
                    out_of_range ? lv_color_hex(0xFF3030) : lv_color_hex(0x25CDE3), LV_PART_MAIN);
            }
        }
        if (ui_LabelTpmsVoltage) {
            if (obd.bat_mv > 0) {
                snprintf(text, sizeof(text), "%d.%d V", obd.bat_mv / 1000,
                         (obd.bat_mv % 1000) / 100);
            } else {
                snprintf(text, sizeof(text), "--.- V");
            }
            if (strcmp(lv_label_get_text(ui_LabelTpmsVoltage), text) != 0)
                lv_label_set_text(ui_LabelTpmsVoltage, text);
            bool voltage_low = obd.bat_mv > 0 && obd.bat_mv < (int32_t)tpms_cfg->tpms_voltage_min_mv;
            lv_obj_set_style_text_color(ui_LabelTpmsVoltage,
                voltage_low ? lv_color_hex(0xFF4545) : lv_color_hex(0xFFFFFF), LV_PART_MAIN);
        }
    }

    /* Generic chart page update: the displayed data item is chosen by chart_source_idx (merges the former oil-pressure/brake-temp pages) */
    if (scr == ui_ScreenPageOilPressure && ui_LabelOilPressureText) {
        static int32_t s_disp_chart = 0;
        static uint8_t s_last_chart_src = 0xFF;
        disp_item_t citem = (disp_item_t)(user_cfg->chart_source_idx % DISP_ITEM_COUNT);
        if (s_last_chart_src != user_cfg->chart_source_idx) {
            s_last_chart_src = user_cfg->chart_source_idx;
            s_disp_chart = 0;  // reset on source switch, avoiding a ramp from the old source's value
        }
        int32_t cval = 0;
        bool cvalid;
        if (IN_SWEEP) {
            int step = ui_ext_sweep_get_step() - 1;
            float r;
            if (step <= SWEEP_STEPS_UP) r = (float)step / (float)SWEEP_STEPS_UP;
            else r = 1.0f;   // hold at max (hold phase)
            cval = disp_item_sweep_value(citem, r);
            cvalid = true;
            s_disp_chart = cval;
            disp_item_set_text(ui_LabelOilPressureText, citem, s_disp_chart, cvalid);
            disp_item_set_value_color(ui_LabelOilPressureText, citem, s_disp_chart, cvalid);
        } else {
            cvalid = disp_item_read_value(citem, clt, iat, oil, load_pct, tps, bat_mv,
                                          oilp_x10, brake_x10, usRpm, ucSpeed, boost_x10, afr_x100, &cval);
            disp_item_update(&s_disp_chart, ui_LabelOilPressureText, citem, cval, cvalid, ANIM_THRESH_TEMP);
        }

        // Feed the chart and refresh only when not sweeping: during the boot sweep the chart stays put (the sweep is for needles/digits; the trend chart does not take part)
        if (!IN_SWEEP) {
            uint32_t now = lv_tick_get();
            if (s_oil_pressure_trend_tick == 0) {
                oil_pressure_trend_init();
                s_oil_pressure_trend_tick = now;
            }
            bool trend_updated = false;
            while ((now - s_oil_pressure_trend_tick) >= OIL_PRESS_TREND_SAMPLE_MS) {
                oil_pressure_trend_push(cvalid ? (int16_t)s_disp_chart : CHART_INVALID);
                s_oil_pressure_trend_tick += OIL_PRESS_TREND_SAMPLE_MS;
                trend_updated = true;
            }
            // the trend buffer only changes on an actual sample (~once per second), so no need to redraw the whole chart every timer tick
            if (trend_updated) oil_pressure_chart_refresh();
        }
    }

    /* Info page update */
    if (scr == ui_ScreenPageInfo && ui_LabelInfoValue[0]) {
        static int32_t s_disp_info[4] = {0};
        static uint8_t s_last_info_map[4] = {0xFF, 0xFF, 0xFF, 0xFF};

        if (ui_LabelInfoFuel && ui_LabelInfoFuelNeed) {
            const uint16_t tank_capacity_dl = vehicle_profile_get_active()->fuel_tank_capacity_dl;
            if (fuel_pct >= 0 && fuel_pct <= 100 && tank_capacity_dl > 0) {
                const uint16_t fuel_dl = (uint16_t)((fuel_pct * tank_capacity_dl + 50) / 100);
                const uint16_t refill_dl = tank_capacity_dl - fuel_dl;
                lv_label_set_text_fmt(ui_LabelInfoFuel, "油量 %d%% 约 %u.%uL",
                                      fuel_pct, fuel_dl / 10, fuel_dl % 10);
                lv_label_set_text_fmt(ui_LabelInfoFuelNeed, "加满 %d%% 约 %u.%uL",
                                      100 - fuel_pct, refill_dl / 10, refill_dl % 10);
            } else {
                lv_label_set_text(ui_LabelInfoFuel, "油量 --% 约 --.-L");
                lv_label_set_text(ui_LabelInfoFuelNeed, "加满 --% 约 --.-L");
            }
        }

        if (IN_SWEEP) {
            int step = ui_ext_sweep_get_step() - 1; // already incremented above
            float r;
            if (step <= SWEEP_STEPS_UP) r = (float)step / (float)SWEEP_STEPS_UP;
            else r = 1.0f;   // hold at max (hold phase)

            for (int i = 0; i < 4; ++i) {
                uint8_t map_idx = user_cfg->info_display_map[i];
                disp_item_t item = (disp_item_t)(map_idx % DISP_ITEM_COUNT);

                if (s_last_info_map[i] != map_idx) {
                    s_last_info_map[i] = map_idx;
                    s_disp_info[i] = 0;  // reset on source switch, avoiding a ramp from the old source's value
                    ui_update_metric_header(ui_LabelInfoName[i], ui_LabelInfoUnit[i], NULL, item);
                }

                int32_t sw = disp_item_sweep_value(item, r);
                disp_item_set_text(ui_LabelInfoValue[i], item, sw, true);
                disp_item_set_value_color(ui_LabelInfoValue[i], item, sw, true);
            }
        } else {
            for (int i = 0; i < 4; ++i) {
                uint8_t map_idx = user_cfg->info_display_map[i];
                disp_item_t item = (disp_item_t)(map_idx % DISP_ITEM_COUNT);

                if (s_last_info_map[i] != map_idx) {
                    s_last_info_map[i] = map_idx;
                    s_disp_info[i] = 0;  // reset on source switch, avoiding a ramp from the old source's value
                    ui_update_metric_header(ui_LabelInfoName[i], ui_LabelInfoUnit[i], NULL, item);
                }

                int32_t value = 0;
                bool valid = disp_item_read_value(item, clt, iat, oil, load_pct, tps, bat_mv, oilp_x10, brake_x10, usRpm, ucSpeed, boost_x10, afr_x100, &value);
                disp_item_update(&s_disp_info[i], ui_LabelInfoValue[i], item, value, valid, ANIM_THRESH_TEMP);
            }
        }
    }

    /* Dynamically update the EasterEgg (device info) page: role + OBD link state + build tag. */
    if (scr == ui_ScreenPageEasterEgg && ui_LabelEasterEggInfo) {
        static char s_last_easteregg_info[192];
        char info_text[192];
        char voltage_text[16];
        const char *mode_str = is_slave ? "从机"
                             : (user_cfg->device_role == ESPNOW_ROLE_MASTER) ? "主机" : "独立";
        const char *conn_name;

        if (is_slave) {
            const char *mname = espnow_link_get_master_name();
            conn_name  = (ble_now && mname[0]) ? mname : "--";
        } else {
            const char *dev_name = elm327_ble_get_connected_name();
            if(!dev_name || dev_name[0] == '\0') dev_name = "Not set";
            conn_name  = dev_name;
        }

        if (esp_bat_mv > 0) {
            snprintf(voltage_text, sizeof(voltage_text), "%d.%d V",
                     (int)(esp_bat_mv / 1000), (int)((esp_bat_mv % 1000) / 100));
        } else {
            strlcpy(voltage_text, "--.- V", sizeof(voltage_text));
        }
        snprintf(info_text, sizeof(info_text),
            "模式: %s\n"
            "连接: %s\n"
            "状态: %s\n"
            "电压: %s\n"
            "固件: %s",
            mode_str, conn_name,
            ble_now ? "已连接" : (is_slave ? "等待" : "未连接"),
            voltage_text, OBD_GAUGE_BUILD_TAG);
        char info_with_battery[224];
        snprintf(info_with_battery, sizeof(info_with_battery),
                 "%s\n电量: %s", info_text,
                 esp_bat_pct >= 0 ? "" : "--%");
        if (esp_bat_pct >= 0) {
            snprintf(info_with_battery, sizeof(info_with_battery),
                     "%s\n电量: %d%%", info_text, esp_bat_pct);
        }
        if (strcmp(s_last_easteregg_info, info_with_battery) != 0) {
            strncpy(s_last_easteregg_info, info_with_battery, sizeof(s_last_easteregg_info));
            s_last_easteregg_info[sizeof(s_last_easteregg_info) - 1] = '\0';
            lv_label_set_text(ui_LabelEasterEggInfo, s_last_easteregg_info);
        }
    }

    /* OTA mode screen: refresh connection status */
    ui_ota_mode_refresh();

#if EXAMPLE_PIN_NUM_BK_LIGHT >= 0
        //wait 500ms before turning on the backlight, so it isn't enabled before init completes; runs once
        if(ucOnlyOnce == 0)
        {
            ulOpenLightTimeCnt++;
            if(ulOpenLightTimeCnt > 400 / 200)
            {
                uint8_t bright = user_cfg->brightness_day;
                if(bright < 10) bright = 100;
                Set_Backlight(bright);
                ESP_LOGD(TAG, "Set LCD backlight to %d%%", bright);
                ulOpenLightTimeCnt = 0;
                ucOnlyOnce = 1;//run once only
            }
        }
#endif

    /* The bottom info bar (TRIP/ODO/MAX/AVG/TIME) belonged to the removed Main page and was removed with it.
       Mileage statistics are still accumulated by a background task and can be shown on other pages or re-attached later. */

    /* ===== Video boot mode (INTRO == 2: VIDEO, the boot_block flashed via the phone app) ===== */
    // Moved to ui_ext.c; returns true while the Logo/video is still showing, so my_timerMain returns early.
    if (ui_ext_boot_video_tick()) return;

    /* ===== Boot flow / Showroom Intro playback (moved to ui_ext.c) ===== */
    ui_ext_intro_tick(is_slave);

    /* ---- RPM over-limit flash warning (migrated to ui_ext.c) ---- */
    ui_ext_rpm_flash_tick(usRpm, IN_SWEEP);

    if (!ui_ext_showroom_is_active()) {
        ui_ext_no_signal_update(ble_now);   // showroom mode is a fake-data demo, no NO SIGNAL hint
    }

    /* ---- Adaptive refresh rate: data pages run fast, static pages stay slow ----
       Only this UI timer's period changes (pure redraw pacing); no OBD/RS485/ESP-NOW query or broadcast is affected. */
    if (timer) {
        static uint32_t s_refresh_ms = 200;
        lv_obj_t *refresh_scr = lv_scr_act();
        uint32_t want_ms = ui_refresh_period_ms_for_screen(refresh_scr, IN_SWEEP, ui_ext_rpm_is_flashing(), ui_ext_rpm_link_ramp_active());
        if (want_ms != s_refresh_ms) {
            s_refresh_ms = want_ms;
            lv_timer_set_period(timer, want_ms);
        }
    }
    #undef IN_SWEEP
}
///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////



///////////////////// FUNCTIONS ////////////////////
void ui_event_logo_background(lv_event_t * e)
{  
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        static uint32_t last_click_tick = 0;
        static uint8_t  click_cnt = 0;
        uint32_t now = lv_tick_get();
        if(now - last_click_tick < 400){
            click_cnt++;
        }else{
            click_cnt = 1;
        }
        last_click_tick = now;

        if(click_cnt >= 2){
            click_cnt = 0;
            ui_nav_show_delete_old(UI_NAV_PAGE_OBD_PROTOCOL,
                                   LV_SCR_LOAD_ANIM_FADE_ON, 300, 0);
            ui_ScreenPageLogo = NULL;
            imageLogo = NULL;
        }  

        ESP_LOGD(TAG, "Logo LV_EVENT_CLICKED");
    }   
}

void ui_event_easter_egg_background(lv_event_t *e)
{
    if (lv_event_get_code(e) == LV_EVENT_CLICKED && !ui_ext_showroom_is_active()) {
        ui_ext_showroom_handle_tap();
    }
}

// OTA mode is a modal radio workflow; the navigation manager owns its exit swipe.
void ui_event_easter_egg_ota_button(lv_event_t *e)
{
    LV_UNUSED(e);
    ui_nav_show(UI_NAV_PAGE_OTA_MODE, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, false);
}

// OTA mode screen: refresh status from the LVGL timer (called every 500ms)
void ui_ota_mode_refresh(void)
{
    if (ui_ScreenPageOTAMode == NULL) return;
    if (ui_LabelOTAModeStatus == NULL) return;

    if (ota_wifi_server_is_busy()) {
        lv_label_set_text(ui_LabelOTAModeStatus, "Receiving update...");
        lv_obj_set_style_text_color(ui_LabelOTAModeStatus, lv_color_hex(0x00CC66), LV_PART_MAIN | LV_STATE_DEFAULT);
    } else if (ota_wifi_server_get_state() == OTA_WIFI_STATE_READY) {
        lv_label_set_text(ui_LabelOTAModeStatus, "WiFi ready — connect your phone");
        lv_obj_set_style_text_color(ui_LabelOTAModeStatus, lv_color_hex(0x00CC66), LV_PART_MAIN | LV_STATE_DEFAULT);
    } else if (ota_wifi_server_get_state() == OTA_WIFI_STATE_IDLE) {
        lv_label_set_text(ui_LabelOTAModeStatus, "Starting WiFi...");
        lv_obj_set_style_text_color(ui_LabelOTAModeStatus, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    } else if (ota_wifi_server_get_state() == OTA_WIFI_STATE_ERROR) {
        lv_label_set_text(ui_LabelOTAModeStatus, "WiFi error");
        lv_obj_set_style_text_color(ui_LabelOTAModeStatus, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    // OPTIMIZATION: Logo is already created and displayed by app_main.c before this function
    // to ensure both Master (with 2MB theme) and Slave show logo simultaneously.
    // Here we only load theme and create other UI elements.

    // Initialize theme partition system AFTER logo is visible
    // This loads the theme from theme_0/theme_1 partition, or falls back to default
    ESP_LOGI(TAG, "Initializing theme partition system");
    esp_err_t theme_ret = theme_engine_init();
    if (theme_ret == ESP_OK) {
        theme_info_t info;
        if (theme_get_info(&info) == ESP_OK) {
            ESP_LOGI(TAG, "Theme loaded: %s v%s by %s", info.name, info.version, info.author);
        }
        // Run test to print detailed theme info
        theme_engine_test();
    } else {
        ESP_LOGW(TAG, "Theme partition system initialization failed, using built-in themes");
    }

    // Load the saved UI theme BEFORE any screen is built, so every screen
    // picks up the active theme's colors at creation time.
    ui_theme_init();
    ui_helpers_init_edge_ring();

    // Keep page creation and route transitions in the central navigation registry.
    ui_nav_register_page(UI_NAV_PAGE_GEAR, &ui_ScreenPageGear, ui_ScreenPageGear_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_THEME_GAUGE, &ui_ScreenPageThemeGauge, ui_ScreenPageThemeGauge_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_RPM, &ui_ScreenPageRpm, ui_ScreenPageRpm_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_SPEED, &ui_ScreenPageSpeed, ui_ScreenPageSpeed_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_TEMP, &ui_ScreenPageTemp, ui_ScreenPageTemp_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_TPMS, &ui_ScreenPageTpms, ui_ScreenPageTpms_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_INFO, &ui_ScreenPageInfo, ui_ScreenPageInfo_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_NEEDLE, &ui_ScreenPageNeedle, ui_ScreenPageNeedle_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_CHART, &ui_ScreenPageOilPressure, ui_ScreenPageOilPressure_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_SKY_GAUGE, &ui_ScreenPageEasterEgg, ui_ScreenPageEasterEgg_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_BLE_SCAN, &ui_ScreenPageBLEScan, ui_ScreenPageBLEScan_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_SETTINGS, &ui_ScreenPageSettings, ui_ScreenPageSettings_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_ALERT_MEDIA, &ui_ScreenPageAlertMedia, ui_ScreenPageAlertMedia_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_MULTI_GAUGE, &ui_ScreenPageMultiGauge, ui_ScreenPageMultiGauge_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_TEMP_CONFIG, &ui_ScreenPageTempCustom, ui_ScreenPageTempCustom_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_TPMS_CONFIG, &ui_ScreenPageTpmsConfig, ui_ScreenPageTpmsConfig_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_INFO_CONFIG, &ui_ScreenPageInfoCustom, ui_ScreenPageInfoCustom_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_NEEDLE_CONFIG, &ui_ScreenPageNeedleConfig, ui_ScreenPageNeedleConfig_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_CHART_CONFIG, &ui_ScreenPageChartConfig, ui_ScreenPageChartConfig_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_CHART_ALARM, &ui_ScreenPageChartAlarm, ui_ScreenPageChartAlarm_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_OIL_WARN, &ui_ScreenPageOilWarn, ui_ScreenPageOilWarn_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_RPM_WARN, &ui_ScreenPageRpmWarn, ui_ScreenPageRpmWarn_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_SPEED_CONFIG, &ui_ScreenPageSpeedConfig, ui_ScreenPageSpeedConfig_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_OBD_PROTOCOL, &ui_ScreenPageODBProtocal, ui_ScreenPageODBProtocal_screen_init);
    ui_nav_register_page(UI_NAV_PAGE_OTA_MODE, &ui_ScreenPageOTAMode, ui_ScreenPageOTAMode_screen_init);
    ui_nav_register_leave_cb(UI_NAV_PAGE_BLE_SCAN, ui_nav_ble_leave);

    // MEMORY OPTIMIZATION: Conditionally create screens based on theme availability
    // If custom theme is loaded, skip built-in gauge pages (Gear/Rpm/Speed/Temp/Needle/OilPressure)
    // and rely on theme-provided pages instead. This saves ~40-60KB RAM for Master mode.
    bool has_custom_theme = false;
    theme_info_t theme_info;
    if (theme_get_info(&theme_info) == ESP_OK) {
        if (theme_info.id[0] != '\0' && strcmp(theme_info.id, "default") != 0) {
            has_custom_theme = true;
            ESP_LOGI(TAG, "Custom theme detected - skipping built-in gauge pages to save RAM");
        }
    }

    if (!has_custom_theme) {
        // No custom theme - create built-in gauge pages
        ui_ScreenPageGear_screen_init();
        ui_ScreenPageRpm_screen_init();
        ui_ScreenPageSpeed_screen_init();
        ui_ScreenPageTemp_screen_init();
        ui_ScreenPageOilPressure_screen_init();
        ui_ScreenPageNeedle_screen_init();
    } else {
        // Custom theme loaded - defer built-in gauge pages (only create if explicitly accessed)
        ui_ScreenPageGear = NULL;
        ui_ScreenPageRpm = NULL;
        ui_ScreenPageSpeed = NULL;
        ui_ScreenPageTemp = NULL;
        ui_ScreenPageOilPressure = NULL;
        ui_ScreenPageNeedle = NULL;
    }

    // System pages are always created (needed for settings/BLE/etc regardless of theme)
    ui_ScreenPageOilWarn_screen_init();
    ui_ScreenPageODBProtocal_screen_init();
    // The Info page is lazy-loaded on demand; its screen pointer must be initialized to NULL
    ui_ScreenPageInfo = NULL;
    ui_ScreenPageTempCustom = NULL;
    ui_ScreenPageTpms = NULL;
    ui_ScreenPageTpmsConfig = NULL;
    ui_ScreenPageInfoCustom = NULL;
    ui_ScreenPageNeedleConfig = NULL;   // config page lazy-loaded
    ui_ScreenPageMultiGauge = NULL;     // triple-gauge settings page lazy-loaded
    ui_ScreenPageAlertMedia = NULL;
    ui_ScreenPageChartConfig = NULL;    // chart data-source selection page lazy-loaded
    ui_ScreenPageChartAlarm = NULL;     // chart alarm settings page lazy-loaded
    ui_ScreenPageIntro = NULL;          // boot animation page lazy-loaded
    ui_ScreenPageThemeGauge = NULL;     // theme-provided gauge page, lazy-loaded (only reachable if the active theme declares "main_gauge")
    ui____initial_actions0 = lv_obj_create(NULL);

    // Pre-create lazy boot pages before the boot switch so they do not build
    // synchronously mid-transition. The other built-in gauge pages are eager.
    if (nvs_cfg_get()->default_page == 1 && ui_ScreenPageInfo == NULL) {
        ui_ScreenPageInfo_screen_init();
    } else if (nvs_cfg_get()->default_page == 7 && ui_ScreenPageTpms == NULL) {
        ui_ScreenPageTpms_screen_init();
    } else if (nvs_cfg_get()->default_page == 8 && ui_ScreenPageMultiGauge == NULL) {
        ui_ScreenPageMultiGauge_screen_init();
    }

    lv_timer_create(my_timerMain,
                    ui_refresh_period_ms_for_screen(lv_scr_act(), false, false, false),
                    NULL);
}

/* OBD protocol page events */
void ui_event_obd_prot_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_LONG_PRESSED){
        usSaveProtTimeCnt = 0;
    }else if(code == LV_EVENT_LONG_PRESSED_REPEAT){
        usSaveProtTimeCnt += 100; // this event fires every 100 ms
        if(usSaveProtTimeCnt >= SAVE_PROTOCOL_TIME){
            usSaveProtTimeCnt = 0;
            nvs_user_cfg_t cfg = *nvs_cfg_get();
            cfg.protocol = lv_roller_get_selected(ui_RollerODBProtocalChoose);
            nvs_cfg_set(&cfg);
            esp_restart();
        }
    }else if(code == LV_EVENT_RELEASED){
        usSaveProtTimeCnt = 0;
    }
}

static void ui_nav_ble_leave(void)
{
    ui_ble_scan_page_leave();
}
