#!/usr/bin/env python3
"""Convert the startup PNG into the LVGL RGB565 logo image."""

from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "main/export_path/images/boot_logo_source.png"
OUTPUT = ROOT / "main/export_path/images/imgBootLogoCustom.c"
WIDTH = 360
HEIGHT = 360


def main():
    source = Image.open(SOURCE).convert("RGB")
    source.thumbnail((WIDTH, HEIGHT), Image.Resampling.LANCZOS)

    canvas = Image.new("RGB", (WIDTH, HEIGHT), (255, 255, 255))
    x = (WIDTH - source.width) // 2
    y = (HEIGHT - source.height) // 2
    canvas.paste(source, (x, y))

    lines = [
        "// Auto-generated by tools/convert_boot_logo.py",
        f"// Source: {SOURCE.name}, fit inside {WIDTH}x{HEIGHT}",
        "// LV_COLOR_16_SWAP=1: RGB565 bytes are stored high byte first.",
        "",
        '#ifdef __has_include',
        '    #if __has_include("lvgl.h")',
        '        #ifndef LV_LVGL_H_INCLUDE_SIMPLE',
        '            #define LV_LVGL_H_INCLUDE_SIMPLE',
        '        #endif',
        '    #endif',
        '#endif',
        '',
        '#if defined(LV_LVGL_H_INCLUDE_SIMPLE)',
        '#include "lvgl.h"',
        '#else',
        '#include "lvgl/lvgl.h"',
        '#endif',
        '',
        '#ifndef LV_ATTRIBUTE_IMG_IMGBOOTLOGOCUSTOM',
        '#define LV_ATTRIBUTE_IMG_IMGBOOTLOGOCUSTOM',
        '#endif',
        '',
        'const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST '
        'LV_ATTRIBUTE_IMG_IMGBOOTLOGOCUSTOM uint8_t imgBootLogoCustom_map[] = {',
    ]

    pixels = canvas.load()
    for y in range(HEIGHT):
        for x0 in range(0, WIDTH, 16):
            row = []
            for x in range(x0, min(x0 + 16, WIDTH)):
                r, g, b = pixels[x, y]
                color = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
                row.extend((f"0x{color >> 8:02X}", f"0x{color & 0xFF:02X}"))
            lines.append("  " + ", ".join(row) + ",")

    lines.extend([
        "};",
        "",
        "const lv_img_dsc_t imgBootLogoCustom = {",
        "  .header.cf = LV_IMG_CF_TRUE_COLOR,",
        "  .header.always_zero = 0,",
        "  .header.reserved = 0,",
        f"  .header.w = {WIDTH},",
        f"  .header.h = {HEIGHT},",
        "  .data_size = sizeof(imgBootLogoCustom_map),",
        "  .data = imgBootLogoCustom_map,",
        "};",
        "",
    ])
    OUTPUT.write_text("\n".join(lines), encoding="ascii")
    print(f"Generated {OUTPUT} from {SOURCE} ({source.width}x{source.height} content)")


if __name__ == "__main__":
    main()
