#!/usr/bin/env python3
"""Generate firmware fuel-tank constants from config/vehicle_fuel_tanks.json."""

import argparse
import json
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("config", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    data = json.loads(args.config.read_text(encoding="utf-8"))
    if data.get("schema_version") != 1 or data.get("unit") != "L":
        raise SystemExit("unsupported vehicle fuel-tank config")

    lines = [
        "/* Auto-generated by tools/gen_vehicle_fuel_config.py. Do not edit. */",
        "#pragma once",
        "",
    ]
    seen_ids = set()
    for vehicle in data.get("vehicles", []):
        identifier = vehicle.get("id")
        capacity_l = vehicle.get("tank_capacity_l")
        if not isinstance(identifier, str) or not identifier or identifier in seen_ids:
            raise SystemExit("each vehicle must have a unique id")
        seen_ids.add(identifier)
        if capacity_l is None:
            capacity_dl = 0
        elif isinstance(capacity_l, (int, float)) and 0 < capacity_l <= 1000:
            capacity_dl = round(capacity_l * 10)
        else:
            raise SystemExit(f"invalid tank capacity for {identifier}")
        lines.append(f"#define VEHICLE_TANK_CAPACITY_{identifier}_DL {capacity_dl}U")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
